 CREATE TABLE DAI_ODS.SCTE_REQUEST     
   (    MESSAGE_ID					VARCHAR2(128) NOT NULL ENABLE,
	    VERSION						VARCHAR2(8)   NOT NULL ENABLE,
	    IDENTITY					VARCHAR2(32)  NOT NULL ENABLE,
	    IDENTITY_VOD_ENDPT_ID		NUMBER(5,0),
	    ADM_DATA					VARCHAR2(64)  NOT NULL ENABLE,
	    ADM_DATA_VOD_ENDPT_ID		NUMBER(5,0),
	    TERMINAL_ADDR				VARCHAR2(128) NOT NULL ENABLE,
	    TARGET_CODE					VARCHAR2(64)  NOT NULL ENABLE,
	    SESSION_ID					VARCHAR2(128) NOT NULL ENABLE,
	    SERVICE_ID					VARCHAR2(32),
	    CONTENT_PROVIDER_ID			VARCHAR2(64),
	    ENTERTAINMENT_PROVIDER_ID	VARCHAR2(64)  NOT NULL ENABLE,
	    ENTERTAINMENT_ASSET_ID		VARCHAR2(64)  NOT NULL ENABLE,
	    ENTERTAINMENT_DURATION		VARCHAR2(32)  NOT NULL ENABLE,
	    CLIENT_DT_STRING			VARCHAR2(32)  NOT NULL ENABLE,
	    CREATED_BY     				VARCHAR2(64),
	    CREATED_DT     				TIMESTAMP(6)  DEFAULT systimestamp NOT NULL ENABLE,
	    LAST_ETL_PROC_NAME     		VARCHAR2(320) NOT NULL ENABLE,
	    LAST_ETL_DT     			TIMESTAMP(6)  DEFAULT systimestamp-30 NOT NULL ENABLE,
	 CONSTRAINT PK_SCTE_REQUEST PRIMARY KEY (MESSAGE_ID) TABLESPACE USERS ENABLE
	)
  TABLESPACE USERS     


 CREATE TABLE DAI_ODS.SCTE_REQUEST_OPPORTUNITY     
   (    REQUEST_MESSAGE_ID			VARCHAR2(128) NOT NULL ENABLE,
	    OPPORTUNITY_ID				VARCHAR2(96)  NOT NULL ENABLE,
	    SERVICE_REG_REF				VARCHAR2(96)  NOT NULL ENABLE,
	    OPPORTUNITY_TYPE			VARCHAR2(16)  NOT NULL ENABLE,
	    OPPORTUNITY_NUMBER			NUMBER(3,0),
	    OPPORTUNITY_DURATION		VARCHAR2(32)  NOT NULL ENABLE,
	    OPPORTUNITY_PLACEMENT_COUNT	NUMBER(3,0),
	    CREATED_BY     				VARCHAR2(64)  NOT NULL ENABLE,
	    CREATED_DT     				TIMESTAMP(6)  NOT NULL ENABLE,
	    LAST_ETL_PROC_NAME     		VARCHAR2(320) NOT NULL ENABLE,
	    LAST_ETL_DT     			TIMESTAMP(6)  NOT NULL ENABLE,
	 CONSTRAINT UQ_SCTE_REQ_OPP UNIQUE (REQUEST_MESSAGE_ID,OPPORTUNITY_ID) TABLESPACE USERS ENABLE
    )
  TABLESPACE USERS


 CREATE TABLE DAI_ODS.SCTE_RESPONSE     
   (	MESSAGE_ID			VARCHAR2(128) NOT NULL ENABLE,
	    REQUEST_MESSAGE_ID	VARCHAR2(128) NOT NULL ENABLE,
	    VERSION				VARCHAR2(8)   NOT NULL ENABLE,
	    IDENTITY			VARCHAR2(32)  NOT NULL ENABLE,
	    STATUS_CODE_CLASS   NUMBER(3,0)   NOT NULL ENABLE,
	    SESSION_ID			VARCHAR2(128) NOT NULL ENABLE,
	    CREATED_BY			VARCHAR2(64)  NOT NULL ENABLE,
	    CREATED_DT			TIMESTAMP(6)  NOT NULL ENABLE,
	    LAST_ETL_PROC_NAME  VARCHAR2(320) NOT NULL ENABLE,
	    LAST_ETL_DT     	TIMESTAMP(6)  NOT NULL ENABLE,
	 CONSTRAINT PK_SCTE_RESPONSE PRIMARY KEY (MESSAGE_ID) TABLESPACE USERS ENABLE
   ) 
  TABLESPACE USERS     


 CREATE TABLE DAI_ODS.SCTE_RESPONSE_PLACEMENT     
   (	RESPONSE_MESSAGE_ID     VARCHAR2(128) NOT NULL ENABLE,
	    SESSION_ID				VARCHAR2(128) NOT NULL ENABLE,
	    DECISION_ID				VARCHAR2(64)  NOT NULL ENABLE,
	    OPPORTUNITY_ID			VARCHAR2(64)  NOT NULL ENABLE,
	    PLACEMENT_ID			VARCHAR2(64),
	    PLACEMENT_ACTION		VARCHAR2(16),
	    PLACEMENT_POS			NUMBER(3,0),
	    TRACKING_ID				VARCHAR2(64),
	    TRACKING_ASSET_ID		VARCHAR2(32),
	    TRACKING_PROVIDER_ID	VARCHAR2(64),
	    CREATED_BY     			VARCHAR2(64)  NOT NULL ENABLE,
	    CREATED_DT     			TIMESTAMP(6)  NOT NULL ENABLE,
	    LAST_ETL_PROC_NAME		VARCHAR2(320) NOT NULL ENABLE,
	    LAST_ETL_DT				TIMESTAMP(6)  NOT NULL ENABLE,
	 CONSTRAINT UQ_SCTE_RESP_PLACEMENT UNIQUE (DECISION_ID, OPPORTUNITY_ID, PLACEMENT_ID) TABLESPACE USERS ENABLE
   ) 
  TABLESPACE  USERS       
  
  
 CREATE TABLE DAI_ODS.SCTE_PSN     
   (    MESSAGE_ID				VARCHAR2(128) NOT NULL ENABLE,
	    VERSION					VARCHAR2(8)   NOT NULL ENABLE,
	    PLAYDATA_IDENTITY		VARCHAR2(32)  NOT NULL ENABLE,
	    PLAYDATA_SESSION_ID		VARCHAR2(128) NOT NULL ENABLE,
	    PLAYDATA_SERVICE_GROUP	VARCHAR2(16),
	    PSE_EVENT_TYPE          VARCHAR2(16)  NOT NULL ENABLE,
	    PSE_STATUSCODE_CLASS    NUMBER(3,0),
	    PSE_EVENT_DT_STRING     VARCHAR2(32)  NOT NULL ENABLE,
	    SPOT_NPT_SCALE     		NUMBER(3,0),
	    SPOT_NPT_VALUE          NUMBER(3,0),
	    ACTUAL_TRACKING_ID      VARCHAR2(64),
	    ACTUAL_ASSET_ID         VARCHAR2(64),
	    ACTUAL_PROVIDER_ID      VARCHAR2(64),
	    CREATED_BY     			VARCHAR2(64)  NOT NULL ENABLE,
	    CREATED_DT     			TIMESTAMP (6) NOT NULL ENABLE,
	    LAST_ETL_PROC_NAME		VARCHAR2(320) NOT NULL ENABLE,
	    LAST_ETL_DT				TIMESTAMP (6) NOT NULL ENABLE
   )
  TABLESPACE USERS

  
  


  


