CREATE TABLE DAI_REPORTING_ODS.SCTE_REQUEST_RAW 
(MESSAGE_ID 				VARCHAR2(128 CHAR), 
 VERSION 					VARCHAR2(8 CHAR), 
 IDENTITY					VARCHAR2(32 CHAR), 
 IDENTITY_VOD_ENDPT_ID		NUMBER(5,0), 
 ADM_DATA					VARCHAR2(64 CHAR), 
 ADM_DATA_VOD_ENDPT_ID		NUMBER(5,0), 
 TERMINAL_ADDR 				VARCHAR2(128 CHAR), 
 TARGET_CODE 				VARCHAR2(64 CHAR), 
 SESSION_ID 				VARCHAR2(128 CHAR), 
 SERVICE_ID 				VARCHAR2(32 CHAR), 
 CONTENT_PROVIDER_ID 		VARCHAR2(64 CHAR), 
 ENTERTAINMENT_PROVIDER_ID	VARCHAR2(64 CHAR), 
 ENTERTAINMENT_ASSET_ID 	VARCHAR2(64 CHAR), 
 ENTERTAINMENT_DURATION		VARCHAR2(32 CHAR), 
 CLIENT_DT_STRING 			VARCHAR2(32 CHAR), 
-- LOCAL_TIMESTAMP  			TIMESTAMP (6) WITH TIME ZONE, 
 CREATED_BY		  			VARCHAR2(64 CHAR), 
 CREATED_DT		  			TIMESTAMP (6) DEFAULT systimestamp, 
 ETL_FILE_NAME	  			VARCHAR2(255 CHAR), 
 LAST_ETL_DT 	  			TIMESTAMP (6) DEFAULT systimestamp
 )
TABLESPACE USERS




CREATE TABLE DAI_REPORTING_ODS.SCTE_REQUEST_OPPTY_RAW
(REQUEST_MESSAGE_ID				VARCHAR2(128 CHAR), 
 OPPORTUNITY_ID					VARCHAR2(96 CHAR), 
 SERVICE_REG_REF				VARCHAR2(96 CHAR), 
 OPPORTUNITY_TYPE 				VARCHAR2(16 CHAR), 
 OPPORTUNITY_NUMBER				NUMBER(3,0), 
 OPPORTUNITY_DURATION			VARCHAR2(32 CHAR), 
 OPPORTUNITY_PLACEMENT_COUNT	NUMBER(3,0), 
 CREATED_BY						VARCHAR2(64 CHAR), 
 CREATED_DT						TIMESTAMP(6), 
 ETL_FILE_NAME					VARCHAR2(255 CHAR), 
 LAST_ETL_DT					TIMESTAMP(6)
)
TABLESPACE USERS








set SERVEROUTPUT on

begin
 for X in (select TABLE_NAME, constraint_name, 
           from USER_TABLES
           where TABLE_NAME like 'SCTE%')
 LOOP
   DBMS_OUTPUT.PUT_LINE('truncate table '||X.TABLE_NAME);
 end LOOP;
end;
/


select * from user_tables

select * from SCTE_REQUEST

select local_timestamp, count(*) item_cnt
from SCTE_REQUEST
group by local_timestamp

