--------------------------------------------------------
--  File created - Wednesday-April-25-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SCTE_RESPONSE_PLACEMENT
--------------------------------------------------------

  CREATE TABLE "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" 
   (	"RESPONSE_MESSAGE_ID" VARCHAR2(128 CHAR), 
	"SESSION_ID" VARCHAR2(128 CHAR), 
	"DECISION_ID" VARCHAR2(128 CHAR), 
	"OPPORTUNITY_ID" VARCHAR2(128 CHAR), 
	"PLACEMENT_ID" VARCHAR2(128 CHAR), 
	"PLACEMENT_ACTION" VARCHAR2(32 CHAR), 
	"PLACEMENT_POS" NUMBER(*,0), 
	"TRACKING_ID" VARCHAR2(128 CHAR), 
	"TRACKING_ASSET_ID" VARCHAR2(128 CHAR), 
	"TRACKING_PROVIDER_ID" VARCHAR2(64 CHAR), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_DT" TIMESTAMP (6), 
	"LAST_ETL_PROC_NAME" VARCHAR2(255 CHAR), 
	"LAST_ETL_DT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_SCTE_RESP_PLACEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAI_ODS"."UQ_SCTE_RESP_PLACEMENT" ON "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" ("DECISION_ID", "OPPORTUNITY_ID", "PLACEMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SCTE_RESPONSE_PLACEMENT
--------------------------------------------------------

  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" MODIFY ("LAST_ETL_DT" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" MODIFY ("LAST_ETL_PROC_NAME" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" MODIFY ("OPPORTUNITY_ID" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" MODIFY ("DECISION_ID" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" MODIFY ("RESPONSE_MESSAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE_PLACEMENT" ADD CONSTRAINT "UQ_SCTE_RESP_PLACEMENT" UNIQUE ("DECISION_ID", "OPPORTUNITY_ID", "PLACEMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

