--------------------------------------------------------
--  File created - Wednesday-April-25-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SCTE_RESPONSE
--------------------------------------------------------

  CREATE TABLE "DAI_ODS"."SCTE_RESPONSE" 
   (	"MESSAGE_ID" VARCHAR2(128 CHAR), 
	"REQUEST_MESSAGE_ID" VARCHAR2(128 CHAR), 
	"VERSION" VARCHAR2(8 CHAR), 
	"IDENTITY" VARCHAR2(255 CHAR), 
	"STATUS_CODE_CLASS" NUMBER(*,0), 
	"SESSION_ID" VARCHAR2(128 CHAR), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_DT" TIMESTAMP (6), 
	"LAST_ETL_PROC_NAME" VARCHAR2(255 CHAR), 
	"LAST_ETL_DT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SCTE_RESPONSE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAI_ODS"."PK_SCTE_RESPONSE" ON "DAI_ODS"."SCTE_RESPONSE" ("MESSAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SCTE_RESPONSE
--------------------------------------------------------

  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" ADD CONSTRAINT "PK_SCTE_RESPONSE" PRIMARY KEY ("MESSAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" MODIFY ("LAST_ETL_DT" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" MODIFY ("LAST_ETL_PROC_NAME" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" MODIFY ("STATUS_CODE_CLASS" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" MODIFY ("IDENTITY" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" MODIFY ("REQUEST_MESSAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "DAI_ODS"."SCTE_RESPONSE" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);

