---### Created:	05/02/2012
---###  Author: Ben Aycrigg
---### Purpose: DAI ETL Testing Tables
-------------------------------------------------------------
select table_name, last_analyzed from user_tables

select object_id, object_type, object_name, created, timestamp, status
from user_objects
where object_type = 'TABLE'
  and object_name like 'SCTE%'

truncate table scte_request

insert into SCTE_REQUEST
select * from SCTE_RQST_TMP
where terminal_addr is not null
  and adm_data is not null
order by message_id, session_id


select count(*) from SCTE_RQST_TMP   ---49
select count(*) from SCTE_REQUEST

select message_id from SCTE_RQST_TMP
minus
select message_id from SCTE_REQUEST
------------------------------------------------------------------------------





--===============================================================================
CREATE TABLE DAI_ODS.SCTE_PSN_TMP 
   (MESSAGE_ID				VARCHAR2(128 CHAR), 
	VERSION					VARCHAR2(8 CHAR)  , 
	PLAYDATA_IDENTITY		VARCHAR2(255 CHAR), 
	PLAYDATA_SESSION_ID 	VARCHAR2(128 CHAR), 
	PLAYDATA_SERVICE_GROUP	VARCHAR2(128 CHAR), 
	PSE_EVENT_TYPE			VARCHAR2(128 CHAR), 
	PSE_STATUSCODE_CLASS	NUMBER(5,0), 
	PSE_EVENT_DT_STRING		VARCHAR2(128 CHAR), 
	PSE_EVENT_LOCAL_DT		TIMESTAMP (6) WITH TIME ZONE, 
--	PSE_EVENT_LOCAL_DATE	DATE, 
--	PSE_EVENT_LOCAL_HOUR	NUMBER(2,0), 
--	PSE_EVENT_LOCAL_OFFSET	NUMBER(3,0), 
--	PSE_EVENT_UTC_DT		TIMESTAMP (6), 
	SPOT_NPT_SCALE			NUMBER, 
	SPOT_NPT_VALUE 			NUMBER, 
	ACTUAL_TRACKING_ID 		VARCHAR2(128 CHAR), 
	ACTUAL_ASSET_ID 		VARCHAR2(128 CHAR), 
	ACTUAL_PROVIDER_ID 		VARCHAR2(64 CHAR), 
	CREATED_BY 				VARCHAR2(255 CHAR), 
	CREATED_DT 				TIMESTAMP (6)     , 
	LAST_ETL_PROC_NAME		VARCHAR2(255 CHAR), 
	LAST_ETL_DT 			TIMESTAMP (6)     
   ) TABLESPACE USERS;

/*
CREATE TABLE DAI_ODS.SCTE_RQST_OPPTY_TMP
   (REQUEST_MESSAGE_ID			VARCHAR2(128 CHAR), 
	OPPORTUNITY_ID				VARCHAR2(128 CHAR), 
	SERVICE_REG_REF				VARCHAR2(128 CHAR), 
	OPPORTUNITY_TYPE			VARCHAR2(32 CHAR) , 
	OPPORTUNITY_NUMBER 			NUMBER(*,0), 
	OPPORTUNITY_DURATION		VARCHAR2(64 CHAR) , 
	OPPORTUNITY_PLACEMENT_COUNT	NUMBER(3,0), 
	CREATED_BY 					VARCHAR2(255 CHAR), 
	CREATED_DT 					TIMESTAMP (6)     , 
	LAST_ETL_PROC_NAME 			VARCHAR2(255 CHAR), 
	LAST_ETL_DT 				TIMESTAMP (6)   , 
--     CONSTRAINT UQ_SCTE_REQ_OPP UNIQUE (REQUEST_MESSAGE_ID, OPPORTUNITY_ID) TABLESPACE USERS ENABLE
   ) TABLESPACE USERS;
*/;
 
CREATE TABLE DAI_ODS.SCTE_RESP_TMP
   (MESSAGE_ID 			VARCHAR2(128 CHAR), 
	REQUEST_MESSAGE_ID	VARCHAR2(128 CHAR), 
	VERSION				VARCHAR2(8 CHAR)  , 
	IDENTITY			VARCHAR2(255 CHAR), 
	STATUS_CODE_CLASS	NUMBER(3,0)       , 
	SESSION_ID			VARCHAR2(128 CHAR), 
	CREATED_BY			VARCHAR2(255 CHAR), 
	CREATED_DT			TIMESTAMP(6)      , 
	LAST_ETL_PROC_NAME	VARCHAR2(255 CHAR), 
	LAST_ETL_DT			TIMESTAMP(6)
--	 CONSTRAINT PK_SCTE_RESPONSE PRIMARY KEY (MESSAGE_ID) TABLESPACE USERS ENABLE
   ) TABLESPACE USERS;

CREATE TABLE DAI_ODS.SCTE_RESP_PLCMT_TMP
   (RESPONSE_MESSAGE_ID  VARCHAR2(128 CHAR), 
	SESSION_ID			 VARCHAR2(128 CHAR), 
	DECISION_ID			 VARCHAR2(128 CHAR), 
	OPPORTUNITY_ID		 VARCHAR2(128 CHAR), 
	PLACEMENT_ID		 VARCHAR2(128 CHAR), 
	PLACEMENT_ACTION	 VARCHAR2(32 CHAR), 
	PLACEMENT_POS		 NUMBER(3,0), 
	TRACKING_ID			 VARCHAR2(128 CHAR), 
	TRACKING_ASSET_ID	 VARCHAR2(128 CHAR), 
	TRACKING_PROVIDER_ID VARCHAR2(64 CHAR), 
	CREATED_BY			 VARCHAR2(255 CHAR), 
	CREATED_DT			 TIMESTAMP(6)      , 
	LAST_ETL_PROC_NAME	 VARCHAR2(255 CHAR), 
	LAST_ETL_DT			 TIMESTAMP(6)
--	 CONSTRAINT UQ_SCTE_RESP_PLACEMENT UNIQUE (DECISION_ID, OPPORTUNITY_ID, PLACEMENT_ID) TABLESPACE USERS ENABLE
   ) TABLESPACE USERS;


/*
Insert Into SCTE_PSN_TMP
select
  MESSAGE_ID, VERSION, PLAYDATA_IDENTITY, PLAYDATA_SESSION_ID, PLAYDATA_SERVICE_GROUP,
  PSE_EVENT_TYPE, PSE_STATUSCODE_CLASS, PSE_EVENT_DT_STRING, PSE_EVENT_LOCAL_DT,
  SPOT_NPT_SCALE, SPOT_NPT_VALUE, ACTUAL_TRACKING_ID, ACTUAL_ASSET_ID,
  ACTUAL_PROVIDER_ID, CREATED_BY, CREATED_DT, LAST_ETL_PROC_NAME, LAST_ETL_DT
from SCTE_PSN;
Insert Into SCTE_RESP_TMP       select * from SCTE_RESPONSE;
Insert Into SCTE_RESP_PLCMT_TMP select * from SCTE_RESPONSE_PLACEMENT;
commit
*/
--===============================================================================