CREATE MATERIALIZED VIEW DAI_REPORTING_ETL.MEDIA_ASSET
 (ID, ASSET_IDSTRING, PROVIDER_ID, TYPE, SEPARATION, DURATION, ISCI, AD_ID, VIDEO_DEF)
ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE DAI_REPORTING_DATA 
  CACHE PARALLEL 2 
BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE DAI_REPORTING_INDEX 
REFRESH FORCE ON COMMIT
WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
USING ENFORCED CONSTRAINTS ENABLE QUERY REWRITE
AS
 SELECT
    MEDIA_ASSET.ID, MEDIA_ASSET.ASSET_IDSTRING, MEDIA_ASSET.PROVIDER_ID, MEDIA_ASSET.TYPE,
	MEDIA_ASSET.SEPARATION, MEDIA_ASSET.DURATION, MEDIA_ASSET.ISCI, MEDIA_ASSET.AD_ID,
	MEDIA_ASSET.VIDEO_DEF
FROM DAI_REPORTING.MEDIA_ASSET

