
INSERT INTO RPT_CAMPAIGN_RUNNING_TOTAL
     ( CAMPAIGN_ID, CAMPAIGN_ITEM_ID, MEDIA_ASSET_ID,
       INSERT_COUNT, VIEW_COUNT, PROGRAMMER, OPERATOR,
       SERVICE_GROUP ) VALUES
     ( 10125, 10166, 10042,
       1, 0, 'iN Demand', 'Time Warner',
       'INT2' );

INSERT INTO RPT_CAMPAIGN_RUNNING_TOTAL
     ( CAMPAIGN_ID, CAMPAIGN_ITEM_ID, MEDIA_ASSET_ID,
       INSERT_COUNT, VIEW_COUNT, PROGRAMMER, OPERATOR,
       SERVICE_GROUP ) VALUES
     ( 10125, 10164, 10003,
       1, 0, 'iN Demand', 'Time Warner',
       'INT2' );

INSERT INTO RPT_CAMPAIGN_RUNNING_TOTAL
     ( CAMPAIGN_ID, CAMPAIGN_ITEM_ID, MEDIA_ASSET_ID,
       INSERT_COUNT, VIEW_COUNT, PROGRAMMER, OPERATOR,
       SERVICE_GROUP ) VALUES
     ( 10095, 10110, 10044,
       1, 0, 'HBO', 'Time Warner',
       'INT2' );
