--------------------------------------------------------
--  File created - Wednesday-April-25-2012   
--------------------------------------------------------
REM INSERTING into DAI_ODS.RPT_AGG_CAMPAIGN_DETAIL
Insert into DAI_ODS.RPT_AGG_CAMPAIGN_DETAIL (CAMPAIGN_ID,CAMPAIGN_ITEM_ID,MEDIA_ASSET_ID,OPERATOR,SERVICE_GROUP,DATE_DIM_ID,INSERT_COUNT,VIEW_COUNT) values (10095,10110,10044,'Time Warner','INT2',1850,5,2);
Insert into DAI_ODS.RPT_AGG_CAMPAIGN_DETAIL (CAMPAIGN_ID,CAMPAIGN_ITEM_ID,MEDIA_ASSET_ID,OPERATOR,SERVICE_GROUP,DATE_DIM_ID,INSERT_COUNT,VIEW_COUNT) values (10125,10164,10003,'Time Warner','INT2',1818,1,1);
Insert into DAI_ODS.RPT_AGG_CAMPAIGN_DETAIL (CAMPAIGN_ID,CAMPAIGN_ITEM_ID,MEDIA_ASSET_ID,OPERATOR,SERVICE_GROUP,DATE_DIM_ID,INSERT_COUNT,VIEW_COUNT) values (10095,10110,10044,'Time Warner','INT2',1816,1,0);
Insert into DAI_ODS.RPT_AGG_CAMPAIGN_DETAIL (CAMPAIGN_ID,CAMPAIGN_ITEM_ID,MEDIA_ASSET_ID,OPERATOR,SERVICE_GROUP,DATE_DIM_ID,INSERT_COUNT,VIEW_COUNT) values (10125,10166,10042,'Time Warner','INT2',1934,1,1);
Insert into DAI_ODS.RPT_AGG_CAMPAIGN_DETAIL (CAMPAIGN_ID,CAMPAIGN_ITEM_ID,MEDIA_ASSET_ID,OPERATOR,SERVICE_GROUP,DATE_DIM_ID,INSERT_COUNT,VIEW_COUNT) values (10125,10164,10003,'Time Warner','INT2',1934,1,1);
Insert into DAI_ODS.RPT_AGG_CAMPAIGN_DETAIL (CAMPAIGN_ID,CAMPAIGN_ITEM_ID,MEDIA_ASSET_ID,OPERATOR,SERVICE_GROUP,DATE_DIM_ID,INSERT_COUNT,VIEW_COUNT) values (10108,10001,10001,'Time Warner','INT2',1817,3,2);
Insert into DAI_ODS.RPT_AGG_CAMPAIGN_DETAIL (CAMPAIGN_ID,CAMPAIGN_ITEM_ID,MEDIA_ASSET_ID,OPERATOR,SERVICE_GROUP,DATE_DIM_ID,INSERT_COUNT,VIEW_COUNT) values (10095,10110,10044,'Time Warner','INT2',1817,4,1);
