/** 05/10/2012
--- recreate 5 SCTE data "Staging" Tables" with revised Data Type specifications
***/

drop table DAI_ODS.SCTE_REQUEST;
drop table DAI_ODS.SCTE_REQUEST_OPPORTUNITY;
drop table DAI_ODS.SCTE_RESPONSE;
drop table DAI_ODS.SCTE_RESPONSE_PLACEMENT;
drop table DAI_ODS.SCTE_PSN;


 CREATE TABLE DAI_ODS.SCTE_REQUEST
   (    MESSAGE_ID				  VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    VERSION					  VARCHAR2(8   CHAR) NOT NULL ENABLE,
	    IDENTITY				  VARCHAR2(32  CHAR) NOT NULL ENABLE,
	    IDENTITY_VOD_ENDPT_ID	  NUMBER(5,0),
	    ADM_DATA				  VARCHAR2(64  CHAR) NOT NULL ENABLE,
	    ADM_DATA_VOD_ENDPT_ID	  NUMBER(5,0),
	    TERMINAL_ADDR			  VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    TARGET_CODE				  VARCHAR2(64  CHAR) NOT NULL ENABLE,
	    SESSION_ID				  VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    SERVICE_ID				  VARCHAR2(32  CHAR),
	    CONTENT_PROVIDER_ID		  VARCHAR2(64  CHAR),
	    ENTERTAINMENT_PROVIDER_ID VARCHAR2(64  CHAR) NOT NULL ENABLE,
	    ENTERTAINMENT_ASSET_ID	  VARCHAR2(64  CHAR) NOT NULL ENABLE,
	    ENTERTAINMENT_DURATION	  VARCHAR2(32  CHAR) NOT NULL ENABLE,
	    CLIENT_DT_STRING		  VARCHAR2(32  CHAR) NOT NULL ENABLE,
        LOCAL_TIMESTAMP           TIMESTAMP with TIME ZONE,		
	    CREATED_BY     			  VARCHAR2(64  CHAR),
	    CREATED_DT     			  TIMESTAMP(6) DEFAULT systimestamp NOT NULL ENABLE,
	    LAST_ETL_PROC_NAME     	  VARCHAR2(320 CHAR) NOT NULL ENABLE,
	    LAST_ETL_DT     		  TIMESTAMP(6) DEFAULT systimestamp NOT NULL ENABLE,
	    CONSTRAINT PK_SCTE_REQUEST PRIMARY KEY (MESSAGE_ID));



 CREATE TABLE DAI_ODS.SCTE_REQUEST_OPPORTUNITY
   (    REQUEST_MESSAGE_ID			VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    OPPORTUNITY_ID				VARCHAR2(96  CHAR) NOT NULL ENABLE,
	    SERVICE_REG_REF				VARCHAR2(96  CHAR) NOT NULL ENABLE,
	    OPPORTUNITY_TYPE			VARCHAR2(16  CHAR) NOT NULL ENABLE,
	    OPPORTUNITY_NUMBER			NUMBER(3,0),
	    OPPORTUNITY_DURATION		VARCHAR2(32  CHAR) NOT NULL ENABLE,
	    OPPORTUNITY_PLACEMENT_COUNT	NUMBER(3,0),
	    CREATED_BY     				VARCHAR2(64  CHAR) NOT NULL ENABLE,
	    CREATED_DT     				TIMESTAMP(6) NOT NULL ENABLE,
	    LAST_ETL_PROC_NAME     		VARCHAR2(320 CHAR) NOT NULL ENABLE,
	    LAST_ETL_DT     			TIMESTAMP(6) NOT NULL ENABLE,
	 CONSTRAINT UQ_SCTE_REQ_OPP UNIQUE (REQUEST_MESSAGE_ID,OPPORTUNITY_ID) ENABLE);


 CREATE TABLE DAI_ODS.SCTE_RESPONSE     
   (	MESSAGE_ID			VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    REQUEST_MESSAGE_ID	VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    VERSION				VARCHAR2(8   CHAR) NOT NULL ENABLE,
	    IDENTITY			VARCHAR2(32  CHAR) NOT NULL ENABLE,
	    STATUS_CODE_CLASS   NUMBER(3,0)  NOT NULL ENABLE,
	    SESSION_ID			VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    CREATED_BY			VARCHAR2(64  CHAR) NOT NULL ENABLE,
	    CREATED_DT			TIMESTAMP(6) NOT NULL ENABLE,
	    LAST_ETL_PROC_NAME  VARCHAR2(320 CHAR) NOT NULL ENABLE,
	    LAST_ETL_DT     	TIMESTAMP(6) NOT NULL ENABLE,
	 CONSTRAINT PK_SCTE_RESPONSE PRIMARY KEY (MESSAGE_ID) ENABLE);


 CREATE TABLE DAI_ODS.SCTE_RESPONSE_PLACEMENT     
   (	RESPONSE_MESSAGE_ID     VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    SESSION_ID				VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    DECISION_ID				VARCHAR2(64  CHAR) NOT NULL ENABLE,
	    OPPORTUNITY_ID			VARCHAR2(64  CHAR) NOT NULL ENABLE,
	    PLACEMENT_ID			VARCHAR2(64  CHAR),
	    PLACEMENT_ACTION		VARCHAR2(16  CHAR),
	    PLACEMENT_POS			NUMBER(3,0),
	    TRACKING_ID				VARCHAR2(64  CHAR),
	    TRACKING_ASSET_ID		VARCHAR2(32  CHAR),
	    TRACKING_PROVIDER_ID	VARCHAR2(64  CHAR),
	    CREATED_BY     			VARCHAR2(64  CHAR) NOT NULL ENABLE,
	    CREATED_DT     			TIMESTAMP(6) NOT NULL ENABLE,
	    LAST_ETL_PROC_NAME		VARCHAR2(320 CHAR) NOT NULL ENABLE,
	    LAST_ETL_DT				TIMESTAMP(6) NOT NULL ENABLE,
	 CONSTRAINT UQ_SCTE_RESP_PLACEMENT UNIQUE (DECISION_ID, OPPORTUNITY_ID, PLACEMENT_ID) ENABLE);

  
  
 CREATE TABLE DAI_ODS.SCTE_PSN     
   (    MESSAGE_ID				VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    VERSION					VARCHAR2(8   CHAR) NOT NULL ENABLE,
	    PLAYDATA_IDENTITY		VARCHAR2(32  CHAR) NOT NULL ENABLE,
	    PLAYDATA_SESSION_ID		VARCHAR2(128 CHAR) NOT NULL ENABLE,
	    PLAYDATA_SERVICE_GROUP	VARCHAR2(16  CHAR),
	    PSE_EVENT_TYPE          VARCHAR2(16  CHAR) NOT NULL ENABLE,
	    PSE_STATUSCODE_CLASS    NUMBER(3,0),
	    PSE_EVENT_DT_STRING     VARCHAR2(32  CHAR) NOT NULL ENABLE,
	    SPOT_NPT_SCALE     		NUMBER(3,0),
	    SPOT_NPT_VALUE          NUMBER(3,0),
	    ACTUAL_TRACKING_ID      VARCHAR2(64  CHAR),
	    ACTUAL_ASSET_ID         VARCHAR2(64  CHAR),
	    ACTUAL_PROVIDER_ID      VARCHAR2(64  CHAR),
	    CREATED_BY     			VARCHAR2(64) NOT NULL ENABLE,
	    CREATED_DT     			TIMESTAMP (6 CHAR) NOT NULL ENABLE,
	    LAST_ETL_PROC_NAME		VARCHAR2(320 CHAR) NOT NULL ENABLE,
	    LAST_ETL_DT				TIMESTAMP(6) NOT NULL ENABLE
   )
  TABLESPACE USERS;

---~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
set serveroutput ON
declare  v_stmt varchar2(300);

begin
DBMS_OUTPUT.enable(1000000);
v_stmt := 'truncate table ';

for T in (select TABLE_NAME
          from user_tables
          where table_name like 'SCTE%TMP')
 LOOP
  DBMS_OUTPUT.PUT_LINE(V_STMT||' '||T.TABLE_NAME);
  execute immediate (V_STMT||t.table_name);
 end loop;
end;

  
  

