--liquibase formatted sql

--changeset jma:003_1 dbms:oracle

-- Comments:
--    Create SCTE_PSN table for XML processing of PlacementStatusNotification messages.
--
CREATE TABLE SCTE_PSN
(MESSAGE_ID		VARCHAR2(128 CHAR) NOT NULL ENABLE,
 VERSION		VARCHAR2(8   CHAR) NOT NULL ENABLE,
 PLAYDATA_IDENTITY	VARCHAR2(32  CHAR) NOT NULL ENABLE,
 PLAYDATA_SESSION_ID	VARCHAR2(128 CHAR) NOT NULL ENABLE,
 PLAYDATA_SERVICE_GROUP	VARCHAR2(16  CHAR),
 PSE_EVENT_TYPE         VARCHAR2(16  CHAR) NOT NULL ENABLE,
 PSE_STATUSCODE_CLASS   NUMBER(3,0),
 PSE_EVENT_DT_STRING    VARCHAR2(32  CHAR) NOT NULL ENABLE,
 LOCAL_TIMESTAMP        TIMESTAMP with TIME ZONE, 
 SPOT_NPT_SCALE     	NUMBER(3,0),
 SPOT_NPT_VALUE         NUMBER(3,0),
 ACTUAL_TRACKING_ID     VARCHAR2(64  CHAR),
 ACTUAL_ASSET_ID        VARCHAR2(64  CHAR),
 ACTUAL_PROVIDER_ID     VARCHAR2(64  CHAR),
 CREATED_BY     	VARCHAR2(64)       NOT NULL ENABLE,
 CREATED_DT     	TIMESTAMP (6)      NOT NULL ENABLE,
 LAST_ETL_PROC_NAME	VARCHAR2(255 CHAR) NOT NULL ENABLE,
 LAST_ETL_DT		TIMESTAMP(6)       NOT NULL ENABLE
 );

